package com.task.entity;

import java.io.Serializable;

/**
 * SumGoodsId generated by MyEclipse Persistence Tools
 */

public class SumGoodsId implements java.io.Serializable {
		private static final long serialVersionUID = 1L;
	// Fields

	private String goodsMarkId;
	private String goodsFormat;
	private String goodsClass;
	private String goodHouseName;//区名
	private String goodsPosition;//库位 
	private String goodsFullname;
	private String goodsUnit;
	private String fcStatus;//封存状态
	private Float sumCount;

	// Constructors

	/** default constructor */
	public SumGoodsId() {
	}

	/** full constructor */
	public SumGoodsId(String goodsMarkId, String goodsFormat,
			String goodsClass, String goodsFullname, String goodsUnit,
			Float sumCount) {
		this.goodsMarkId = goodsMarkId;
		this.goodsFormat = goodsFormat;
		this.goodsClass = goodsClass;
		this.goodsFullname = goodsFullname;
		this.goodsUnit = goodsUnit;
		this.sumCount = sumCount;
	}

	// Property accessors

	public String getGoodsMarkId() {
		return this.goodsMarkId;
	}

	public void setGoodsMarkId(String goodsMarkId) {
		this.goodsMarkId = goodsMarkId;
	}

	public String getGoodsFormat() {
		return this.goodsFormat;
	}

	public void setGoodsFormat(String goodsFormat) {
		this.goodsFormat = goodsFormat;
	}

	public String getGoodsClass() {
		return this.goodsClass;
	}

	public void setGoodsClass(String goodsClass) {
		this.goodsClass = goodsClass;
	}

	public String getGoodsFullname() {
		return this.goodsFullname;
	}

	public void setGoodsFullname(String goodsFullname) {
		this.goodsFullname = goodsFullname;
	}

	public String getGoodsUnit() {
		return this.goodsUnit;
	}

	public void setGoodsUnit(String goodsUnit) {
		this.goodsUnit = goodsUnit;
	}

	public Float getSumCount() {
		return this.sumCount;
	}

	public void setSumCount(Float sumCount) {
		this.sumCount = sumCount;
	}
	

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SumGoodsId))
			return false;
		SumGoodsId castOther = (SumGoodsId) other;

		return ((this.getGoodsMarkId() == castOther.getGoodsMarkId()) || (this
				.getGoodsMarkId() != null
				&& castOther.getGoodsMarkId() != null && this.getGoodsMarkId()
				.equals(castOther.getGoodsMarkId())))
				&& ((this.getGoodsFormat() == castOther.getGoodsFormat()) || (this
						.getGoodsFormat() != null
						&& castOther.getGoodsFormat() != null && this
						.getGoodsFormat().equals(castOther.getGoodsFormat())))
				&& ((this.getGoodsClass() == castOther.getGoodsClass()) || (this
						.getGoodsClass() != null
						&& castOther.getGoodsClass() != null && this
						.getGoodsClass().equals(castOther.getGoodsClass())))
				&& ((this.getGoodHouseName() == castOther.getGoodHouseName()) || (this
								.getGoodHouseName() != null
								&& castOther.getGoodHouseName() != null && this
								.getGoodHouseName().equals(castOther.getGoodHouseName())))
				&& ((this.getGoodsPosition() == castOther.getGoodsPosition()) || (this
										.getGoodsPosition() != null
										&& castOther.getGoodsPosition() != null && this
										.getGoodsPosition().equals(castOther.getGoodsPosition())))
				&& ((this.getGoodsFullname() == castOther.getGoodsFullname()) || (this
						.getGoodsFullname() != null
						&& castOther.getGoodsFullname() != null && this
						.getGoodsFullname()
						.equals(castOther.getGoodsFullname())))
				&& ((this.getGoodsUnit() == castOther.getGoodsUnit()) || (this
						.getGoodsUnit() != null
						&& castOther.getGoodsUnit() != null && this
						.getGoodsUnit().equals(castOther.getGoodsUnit())))
				&& ((this.getSumCount() == castOther.getSumCount()) || (this
						.getSumCount() != null
						&& castOther.getSumCount() != null && this
						.getSumCount().equals(castOther.getSumCount())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getGoodsMarkId() == null ? 0 : this.getGoodsMarkId()
						.hashCode());
		result = 37
				* result
				+ (getGoodsFormat() == null ? 0 : this.getGoodsFormat()
						.hashCode());
		result = 37
				* result
				+ (getGoodsClass() == null ? 0 : this.getGoodsClass()
						.hashCode());
		result = 37
				* result
				+ (getGoodsFullname() == null ? 0 : this.getGoodsFullname()
						.hashCode());
		result = 37 * result
				+ (getGoodsUnit() == null ? 0 : this.getGoodsUnit().hashCode());
		result = 37 * result
				+ (getSumCount() == null ? 0 : this.getSumCount().hashCode());
		return result;
	}

	public String getGoodHouseName() {
		return goodHouseName;
	}

	public void setGoodHouseName(String goodHouseName) {
		this.goodHouseName = goodHouseName;
	}

	public String getGoodsPosition() {
		return goodsPosition;
	}

	public void setGoodsPosition(String goodsPosition) {
		this.goodsPosition = goodsPosition;
	}

	public String getFcStatus() {
		return fcStatus;
	}

	public void setFcStatus(String fcStatus) {
		this.fcStatus = fcStatus;
	}
	

}