package com.task.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import com.alibaba.fastjson.annotation.JSONField;
import com.task.util.FieldMeta;

/**
 * OaAppDetail generated by MyEclipse Persistence Tools
 */
/****
 * 采购申报明细
 * 表名:oa_appDetail
 */
public class OaAppDetail  implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	@FieldMeta(name = "物料编码")
	private String wlcode;//物料编码
	@FieldMeta(name = "编号")
	private String detailOrdNumber;// 编号，与OaApplyForm 对应-----------
	@FieldMeta(name = "类型")
	private String detailChildClass;// 类型（办公用品，金属五金，杂品）
	@FieldMeta(name = "物品编号")
	private String detailSeqNum;// 物品编号（SBB+月份+序号（0001））----
	@FieldMeta(name = "物品名称")
	private String detailAppName;// 物品名称 ------
	private String detailMarkId;// 件号（加工产品）
	@FieldMeta(name = "规格")
	private String detailFormat;// 规格---
	@FieldMeta(name = "单位")
	private String detailUnit;// 单位---
	@FieldMeta(name = "数量")
	private Float detailCount;// 数量（申报）---
	private Float rgdetailCount;// 入柜数量（申报）---

	private Float detailReceveCount;// 数量（采购）
	private String detailAppDate;// 申请时间---
	private String detailFrockNum;
	private String detailModel;// 车型
	private String detailFunction;// 型别
	@FieldMeta(name = "预算单价")
	private Float detailBudgetMoney;// 预算单价（报修和采购需填）---
	private Float detailRealMoney;// 实际金额（总）入库时计算
	private String detailRecStand;
	private String detailAdviseComp;// 建议厂家
	private String detailIsBusy;// 是否加急--是
	private String detailDate;// 不用
	private Float detailPrice;// 实际单价
	private String detailMore1;
	private String detailExamPrePath;// 审批路径
	private String detailExamRealPath;// 实际审批路径
	private String detailNextSign;// 下一个审批节点
	private String detailStatus;// 状态（预申请，审批，同意，采购中，待入库，入库，付款）----
	private String wareWei;// 库位
	private String detailMore2;
	private String detailTimer;
	private String detailClass;// 申请类别 项目，普通，信息
	private String detailItemId;// 项目编号
	@FieldMeta(name = "申报部门")
	private String detailAppDept;// 申报部门---设备
	@FieldMeta(name = "计划月份")
	private String detailPlanMon;// 计划月份
	private String detailPlanAcco;// 计划依据======
	@FieldMeta(name = "到货期限")
	private String detailArrDate;// 到货期限
	private String detailBarcode;// 条码
	private String detailarrivaltime;// 到货时间

	private String status;// 状态(入完，未入完)

	private Set<Storage> storages = new HashSet<Storage>();// 综合库入库表

	private Integer deptMonthBudgetID;// 部门月度申报ID
	private String budgetMonth;// 预算月份
	private OaPrepareApply prepareApply;// 预申请
	private OaApplyForm applyForm;// 采购执行单

	private Integer epId;
	private String appayTag;// 申请人级别（个人，经理，副总，总经理）
	private String classNames;//前端显示

	/*
	 * private List<OaAppDetail> listTest;
	 * 
	 * 
	 * public List<OaAppDetail> getListTest() { return listTest; } public void
	 * setListTest(List<OaAppDetail> listTest) { this.listTest = listTest; }
	 */

	public Integer getEpId() {
		return epId;
	}

	public void setEpId(Integer epId) {
		this.epId = epId;
	}

	public String getWareWei() {
		return wareWei;
	}

	public void setWareWei(String wareWei) {
		this.wareWei = wareWei;
	}

	public Float getRgdetailCount() {
		return rgdetailCount;
	}

	public void setRgdetailCount(Float rgdetailCount) {
		this.rgdetailCount = rgdetailCount;
	}

	public String getClassNames() {
		return classNames;
	}

	public void setClassNames(String classNames) {
		this.classNames = classNames;
	}

	public String getDetailarrivaltime() {
		return detailarrivaltime;
	}

	public void setDetailarrivaltime(String detailarrivaltime) {
		this.detailarrivaltime = detailarrivaltime;
	}

	public String getDetailBarcode() {
		return detailBarcode;
	}

	public void setDetailBarcode(String detailBarcode) {
		this.detailBarcode = detailBarcode;
	}

	public String getDetailArrDate() {
		return detailArrDate;
	}

	public void setDetailArrDate(String detailArrDate) {
		this.detailArrDate = detailArrDate;
	}

	public String getDetailPlanMon() {
		return detailPlanMon;
	}

	public void setDetailPlanMon(String detailPlanMon) {
		this.detailPlanMon = detailPlanMon;
	}

	public String getDetailPlanAcco() {
		return detailPlanAcco;
	}

	public void setDetailPlanAcco(String detailPlanAcco) {
		this.detailPlanAcco = detailPlanAcco;
	}

	public OaAppDetail() {
	}

	public OaAppDetail(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDetailOrdNumber() {
		return this.detailOrdNumber;
	}

	public void setDetailOrdNumber(String detailOrdNumber) {
		this.detailOrdNumber = detailOrdNumber;
	}

	public String getDetailClass() {
		return this.detailClass;
	}

	public void setDetailClass(String detailClass) {
		this.detailClass = detailClass;
	}

	public String getDetailChildClass() {
		return this.detailChildClass;
	}

	public void setDetailChildClass(String detailChildClass) {
		this.detailChildClass = detailChildClass;
	}

	public String getDetailSeqNum() {
		return this.detailSeqNum;
	}

	public void setDetailSeqNum(String detailSeqNum) {
		this.detailSeqNum = detailSeqNum;
	}

	public String getDetailAppName() {
		return this.detailAppName;
	}

	public void setDetailAppName(String detailAppName) {
		this.detailAppName = detailAppName;
	}

	public String getDetailMarkId() {
		return this.detailMarkId;
	}

	public void setDetailMarkId(String detailMarkId) {
		this.detailMarkId = detailMarkId;
	}

	public String getDetailFormat() {
		return this.detailFormat;
	}

	public void setDetailFormat(String detailFormat) {
		this.detailFormat = detailFormat;
	}

	public String getDetailUnit() {
		return this.detailUnit;
	}

	public void setDetailUnit(String detailUnit) {
		this.detailUnit = detailUnit;
	}

	public Float getDetailCount() {
		return this.detailCount;
	}

	public void setDetailCount(Float detailCount) {
		this.detailCount = detailCount;
	}

	public Float getDetailReceveCount() {
		return this.detailReceveCount;
	}

	public void setDetailReceveCount(Float detailReceveCount) {
		this.detailReceveCount = detailReceveCount;
	}

	public String getDetailAppDate() {
		return this.detailAppDate;
	}

	public void setDetailAppDate(String detailAppDate) {
		this.detailAppDate = detailAppDate;
	}

	public String getDetailFrockNum() {
		return this.detailFrockNum;
	}

	public void setDetailFrockNum(String detailFrockNum) {
		this.detailFrockNum = detailFrockNum;
	}

	public String getDetailModel() {
		return this.detailModel;
	}

	public void setDetailModel(String detailModel) {
		this.detailModel = detailModel;
	}

	public String getDetailFunction() {
		return this.detailFunction;
	}

	public void setDetailFunction(String detailFunction) {
		this.detailFunction = detailFunction;
	}

	public Float getDetailBudgetMoney() {
		return this.detailBudgetMoney;
	}

	public void setDetailBudgetMoney(Float detailBudgetMoney) {
		this.detailBudgetMoney = detailBudgetMoney;
	}

	public Float getDetailRealMoney() {
		return this.detailRealMoney;
	}

	public void setDetailRealMoney(Float detailRealMoney) {
		this.detailRealMoney = detailRealMoney;
	}

	public String getDetailRecStand() {
		return this.detailRecStand;
	}

	public void setDetailRecStand(String detailRecStand) {
		this.detailRecStand = detailRecStand;
	}

	public String getDetailAdviseComp() {
		return this.detailAdviseComp;
	}

	public void setDetailAdviseComp(String detailAdviseComp) {
		this.detailAdviseComp = detailAdviseComp;
	}

	public String getDetailIsBusy() {
		return this.detailIsBusy;
	}

	public void setDetailIsBusy(String detailIsBusy) {
		this.detailIsBusy = detailIsBusy;
	}

	public String getDetailDate() {
		return this.detailDate;
	}

	public void setDetailDate(String detailDate) {
		this.detailDate = detailDate;
	}

	public Float getDetailPrice() {
		return this.detailPrice;
	}

	public void setDetailPrice(Float detailPrice) {
		this.detailPrice = detailPrice;
	}

	public String getDetailMore1() {
		return this.detailMore1;
	}

	public void setDetailMore1(String detailMore1) {
		this.detailMore1 = detailMore1;
	}

	public String getDetailExamPrePath() {
		return detailExamPrePath;
	}

	public void setDetailExamPrePath(String detailExamPrePath) {
		this.detailExamPrePath = detailExamPrePath;
	}

	public String getDetailExamRealPath() {
		return detailExamRealPath;
	}

	public void setDetailExamRealPath(String detailExamRealPath) {
		this.detailExamRealPath = detailExamRealPath;
	}

	public String getDetailNextSign() {
		return detailNextSign;
	}

	public void setDetailNextSign(String detailNextSign) {
		this.detailNextSign = detailNextSign;
	}

	public String getDetailStatus() {
		return this.detailStatus;
	}

	public void setDetailStatus(String detailStatus) {
		this.detailStatus = detailStatus;
	}

	public String getDetailMore2() {
		return this.detailMore2;
	}

	public void setDetailMore2(String detailMore2) {
		this.detailMore2 = detailMore2;
	}

	public String getDetailTimer() {
		return this.detailTimer;
	}

	public void setDetailTimer(String detailTimer) {
		this.detailTimer = detailTimer;
	}

	// 重写equals方法
	/*
	 * public boolean equals(Object obj){ if(this==obj){ return true; }
	 * if(obj!=null && obj.getClass() == OaAppDetail.class){ OaAppDetail oaApp =
	 * (OaAppDetail)obj;
	 * if(this.getDetailSeqNum().equals(oaApp.getDetailSeqNum())){ return true;
	 * } } return false; } //根据DetailSeqNum属性来计算hashCode public int hashCode(){
	 * return detailSeqNum.hashCode(); }
	 */
	public String getDetailItemId() {
		return detailItemId;
	}

	public void setDetailItemId(String detailItemId) {
		this.detailItemId = detailItemId;
	}

	public String getDetailAppDept() {
		return detailAppDept;
	}

	public void setDetailAppDept(String detailAppDept) {
		this.detailAppDept = detailAppDept;
	}

	@JSONField(serialize = false)
	public Set<Storage> getStorages() {
		return storages;
	}

	public void setStorages(Set<Storage> storages) {
		this.storages = storages;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getDeptMonthBudgetID() {
		return deptMonthBudgetID;
	}

	public void setDeptMonthBudgetID(Integer deptMonthBudgetID) {
		this.deptMonthBudgetID = deptMonthBudgetID;
	}

	@JSONField(serialize = false)
	public OaPrepareApply getPrepareApply() {
		return prepareApply;
	}

	public void setPrepareApply(OaPrepareApply prepareApply) {
		this.prepareApply = prepareApply;
	}

	@JSONField(serialize = false)
	public OaApplyForm getApplyForm() {
		return applyForm;
	}

	public void setApplyForm(OaApplyForm applyForm) {
		this.applyForm = applyForm;
	}

	public String getBudgetMonth() {
		return budgetMonth;
	}

	public void setBudgetMonth(String budgetMonth) {
		this.budgetMonth = budgetMonth;
	}

	public String getAppayTag() {
		return appayTag;
	}

	public void setAppayTag(String appayTag) {
		this.appayTag = appayTag;
	}

	public String getWlcode() {
		return wlcode;
	}

	public void setWlcode(String wlcode) {
		this.wlcode = wlcode;
	}

}
