package com.task.entity;

import java.util.HashSet;
import java.util.Set;

import com.alibaba.fastjson.annotation.JSONField;
import com.task.util.FieldMeta;

/**
 * TaHkHuikuan generated by MyEclipse Persistence Tools
 */
/***
 * @表名 ta_hk_huikuan
 */
public class TaHkHuikuan implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@FieldMeta(name="开票编号")
	private String hkNum;// 回款编号
	private String hkOrder;// 订单号
	private String hkAppPayDate;
	@FieldMeta(name="客户名称")
	private String hkClientComp;
	@FieldMeta(name="关联人")
	private String hkClientName;
	private String hkApplier;
	private String hkApplyDate;
	private Float hkApplyCount;
	private String hkNoticeFile;
	private String hkPreNotPath;
	private String hkRelNotPath;
	private String hkNotOverTime;
	@FieldMeta(name="状态")
	private String hkStatus;
	private String hkBiller;
	@FieldMeta(name="开票金额")
	private Float hkBillMoney;
	private String hkBillTime;
	private Integer hkPayCycle;// 回款周期
	private Integer hkCountDown;// 倒计时
	private String lastTime;//回款期限
	private String kpTime;//开票时间
	private String checkTime;//核对发票信息时间，即申请开票时间
	private String overTime;//回款完成时间
	private String hkInvoiceFile;
	private String hkInvoPrePath;
	private String hkInvoRelPath;
	private String hkInvoOverTime;
	private String hkZhuikuanren;
	private Float hkTrackerTotMoney;
	private Float hkTrackRate;
	private String hkBackAuditA;
	private String hkBackAuditB;
	private String hkMore;
	private String hkMoneyUnit;// 币种
	private Float zhekou;// 折扣金额
	private Integer epId;// 审批流程Id
	private Integer scpId;// 收款汇总id
	private Set taHkSellStas = new HashSet(0);// 开票出库统计明细表
	private Set taHkHkInvoices = new HashSet(0);// 发票发票信息明细表

	// Constructors

	/** default constructor */
	public TaHkHuikuan() {
	}

	public Integer getEpId() {
		return epId;
	}

	public void setEpId(Integer epId) {
		this.epId = epId;
	}

	/** minimal constructor */
	public TaHkHuikuan(String hkNum, String hkStatus) {
		this.hkNum = hkNum;
		this.hkStatus = hkStatus;
	}

	public String getHkMoneyUnit() {
		return hkMoneyUnit;
	}

	public void setHkMoneyUnit(String hkMoneyUnit) {
		this.hkMoneyUnit = hkMoneyUnit;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getHkNum() {
		return this.hkNum;
	}

	public void setHkNum(String hkNum) {
		this.hkNum = hkNum;
	}

	public String getHkOrder() {
		return this.hkOrder;
	}

	public void setHkOrder(String hkOrder) {
		this.hkOrder = hkOrder;
	}

	public String getHkAppPayDate() {
		return this.hkAppPayDate;
	}

	public void setHkAppPayDate(String hkAppPayDate) {
		this.hkAppPayDate = hkAppPayDate;
	}

	public String getHkClientComp() {
		return this.hkClientComp;
	}

	public void setHkClientComp(String hkClientComp) {
		this.hkClientComp = hkClientComp;
	}

	public String getHkClientName() {
		return this.hkClientName;
	}

	public void setHkClientName(String hkClientName) {
		this.hkClientName = hkClientName;
	}

	public String getHkApplier() {
		return this.hkApplier;
	}

	public void setHkApplier(String hkApplier) {
		this.hkApplier = hkApplier;
	}

	public String getHkApplyDate() {
		return this.hkApplyDate;
	}

	public void setHkApplyDate(String hkApplyDate) {
		this.hkApplyDate = hkApplyDate;
	}

	public Float getHkApplyCount() {
		return this.hkApplyCount;
	}

	public void setHkApplyCount(Float hkApplyCount) {
		this.hkApplyCount = hkApplyCount;
	}

	public String getHkNoticeFile() {
		return this.hkNoticeFile;
	}

	public void setHkNoticeFile(String hkNoticeFile) {
		this.hkNoticeFile = hkNoticeFile;
	}

	public String getHkPreNotPath() {
		return this.hkPreNotPath;
	}

	public void setHkPreNotPath(String hkPreNotPath) {
		this.hkPreNotPath = hkPreNotPath;
	}

	public String getHkRelNotPath() {
		return this.hkRelNotPath;
	}

	public void setHkRelNotPath(String hkRelNotPath) {
		this.hkRelNotPath = hkRelNotPath;
	}

	public String getHkNotOverTime() {
		return this.hkNotOverTime;
	}

	public void setHkNotOverTime(String hkNotOverTime) {
		this.hkNotOverTime = hkNotOverTime;
	}

	public String getHkStatus() {
		return this.hkStatus;
	}

	public void setHkStatus(String hkStatus) {
		this.hkStatus = hkStatus;
	}

	public String getHkBiller() {
		return this.hkBiller;
	}

	public void setHkBiller(String hkBiller) {
		this.hkBiller = hkBiller;
	}

	public Float getHkBillMoney() {
		if (null != hkBillMoney) {
			return Float.parseFloat(String.format("%.2f", hkBillMoney));
		}
		return this.hkBillMoney;
	}

	public void setHkBillMoney(Float hkBillMoney) {
		this.hkBillMoney = hkBillMoney;
	}

	public String getHkBillTime() {
		return this.hkBillTime;
	}

	public void setHkBillTime(String hkBillTime) {
		this.hkBillTime = hkBillTime;
	}

	public Integer getHkPayCycle() {
		return this.hkPayCycle;
	}

	public void setHkPayCycle(Integer hkPayCycle) {
		this.hkPayCycle = hkPayCycle;
	}

	public String getHkInvoiceFile() {
		return this.hkInvoiceFile;
	}

	public void setHkInvoiceFile(String hkInvoiceFile) {
		this.hkInvoiceFile = hkInvoiceFile;
	}

	public String getHkInvoPrePath() {
		return this.hkInvoPrePath;
	}

	public void setHkInvoPrePath(String hkInvoPrePath) {
		this.hkInvoPrePath = hkInvoPrePath;
	}

	public String getHkInvoRelPath() {
		return this.hkInvoRelPath;
	}

	public void setHkInvoRelPath(String hkInvoRelPath) {
		this.hkInvoRelPath = hkInvoRelPath;
	}

	public String getHkInvoOverTime() {
		return this.hkInvoOverTime;
	}

	public void setHkInvoOverTime(String hkInvoOverTime) {
		this.hkInvoOverTime = hkInvoOverTime;
	}

	public String getHkZhuikuanren() {
		return this.hkZhuikuanren;
	}

	public void setHkZhuikuanren(String hkZhuikuanren) {
		this.hkZhuikuanren = hkZhuikuanren;
	}

	public Float getHkTrackerTotMoney() {
		return this.hkTrackerTotMoney;
	}

	public void setHkTrackerTotMoney(Float hkTrackerTotMoney) {
		this.hkTrackerTotMoney = hkTrackerTotMoney;
	}

	public Float getHkTrackRate() {
		return this.hkTrackRate;
	}

	public void setHkTrackRate(Float hkTrackRate) {
		this.hkTrackRate = hkTrackRate;
	}

	public String getHkBackAuditA() {
		return this.hkBackAuditA;
	}

	public void setHkBackAuditA(String hkBackAuditA) {
		this.hkBackAuditA = hkBackAuditA;
	}

	public String getHkBackAuditB() {
		return this.hkBackAuditB;
	}

	public void setHkBackAuditB(String hkBackAuditB) {
		this.hkBackAuditB = hkBackAuditB;
	}

	public String getHkMore() {
		return this.hkMore;
	}

	public void setHkMore(String hkMore) {
		this.hkMore = hkMore;
	}

	@JSONField(serialize = false)
	public Set getTaHkSellStas() {
		return this.taHkSellStas;
	}

	public void setTaHkSellStas(Set taHkSellStas) {
		this.taHkSellStas = taHkSellStas;
	}

	@JSONField(serialize = false)
	public Set getTaHkHkInvoices() {
		return this.taHkHkInvoices;
	}

	public void setTaHkHkInvoices(Set taHkHkInvoices) {
		this.taHkHkInvoices = taHkHkInvoices;
	}

	public Integer getHkCountDown() {
		return hkCountDown;
	}

	public void setHkCountDown(Integer hkCountDown) {
		this.hkCountDown = hkCountDown;
	}

	public Float getZhekou() {
		/*
		 * if(null!=zhekou){ return Float.parseFloat(String.format("%.2f",
		 * "zhekou")); }
		 */
		return zhekou;
	}

	public void setZhekou(Float zhekou) {
		this.zhekou = zhekou;
	}

	public String getLastTime() {
		return lastTime;
	}

	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	public String getKpTime() {
		return kpTime;
	}

	public void setKpTime(String kpTime) {
		this.kpTime = kpTime;
	}

	public String getOverTime() {
		return overTime;
	}

	public void setOverTime(String overTime) {
		this.overTime = overTime;
	}

	public String getCheckTime() {
		return checkTime;
	}

	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	public Integer getScpId() {
		return scpId;
	}

	public void setScpId(Integer scpId) {
		this.scpId = scpId;
	}
	

}
